apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver 
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
      annotations:
        "opencontrail.org/network": '[
             {"domain":"default-domain", "project": "default", "name": "right-network"}
             ]'
    spec:
      containers:
      - name: webserver
        image: savvythru/contrail-frontend-app
        securityContext:
           privileged: true
        ports:
        - containerPort: 80
